#!/bin/bash
### ---
### name: 'aggregateResults'
### outputs:
### - 'weighted_f1_results.tsv'
### - 'label_f1_results.tsv'
### - '**factor**tsv'
### - '**summary.tsv'
### - '**png'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/f7/ecdb41cb9f4502d00ccd23ca9cbda2/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/f7/ecdb41cb9f4502d00ccd23ca9cbda2/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f ref_50_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv
    rm -f ref_50_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv
    rm -f ref_50_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv
    rm -f ref_50_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv
    rm -f ref_50_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv
    rm -f ref_50_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv
    rm -f ref_500_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv
    rm -f ref_50_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv
    rm -f ref_100_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv
    rm -f ref_50_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/02/15fabcf764548aefb983f870df0420/ref_50_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/fb/22bd4f64a5928b6d6a0e941d338932/ref_50_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/7c/c41b70415ceddc63c556b12cd86e14/ref_100_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/e7/907002e60beb6beaec77dab3c9a07b/ref_500_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/0b/27d9c06e516df2d1ff8249782e243e/ref_50_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/dc/66f0bd0e11104f2b2682f3c96eb7bf/ref_50_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/63/a36c05c46b0633c72c25fa48ec8c4c/ref_100_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/f3/83e65ab2f0b62428eb6f9ec61238e3/ref_500_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/56/dc62d39d2c51bd695e72e67854bb7c/ref_50_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/bc/a991ce67b95a9e2f08a4cc0f061841/ref_500_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/46/9ee21bdd345e2149f0d7e656ac8da7/ref_500_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0.15_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/fd/dbb7eb9d4ba80b45c42ca34cbaef5e/ref_500_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/59/10908b439fb09f27f0d716cac67945/ref_100_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/22/3c4d414f14109d408b601f4754f846/ref_100_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/b6/b51460cc82d10b0366064bbf1f421d/ref_500_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/2a/ec6e76da876ba097b658d60c7edff9/ref_50_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/0a/d44bc7a765205134feb1c342331d8f/ref_500_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0.25_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/1b/848b5f2c529c3902c06c928e4551b8/ref_100_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/32/2ab12ce55fa2a09f04068d911f3634/ref_100_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/ba/21755892081964f492fed1e20acd57/ref_500_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv ref_500_query_null_cutoff_0.5_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/9a/00211b580dfdb86837b4a049c624f3/ref_50_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0.05_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/1f/8fcdf7deb065dcc2cb857d754ab1df/ref_100_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0.2_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/4c/954c2bea027d199a3dd27aa25d2968/ref_100_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv ref_100_query_null_cutoff_0.1_refsplit_dataset_id_f1_results.tsv
    ln -s /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/7b/39cfb73b55adf97f6e58bd08c248f7/ref_50_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv ref_50_query_null_cutoff_0.75_refsplit_dataset_id_f1_results.tsv
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /space/grp/rschwartz/rschwartz/evaluation_summary.nf/hsap_2024/f7/ecdb41cb9f4502d00ccd23ca9cbda2/.command.begin
    set +u
    # conda environment
    source $(conda info --json | awk '/conda_prefix/ { gsub(/"|,/, "", $2); print $2 }')/bin/activate /home/rschwartz/anaconda3/envs/scanpyenv
    set -u
    export PATH="$PATH:/space/grp/rschwartz/rschwartz/evaluation_summary.nf/bin"
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
